travis:
  secure:
    BINSTAR_TOKEN: Lbxs8DKH4O8JOqPzf1IXlNDtKQrEv/yVNhR2hoeMVmfQ1oYCKtdYc8TFpYeMofJvACIE15eU3YYbGJW6zkwuFMEEP1cXY3CtEZQkcwT6NZswJ4bS1X6J2JXGzLjSDXFSd1c9sFfHgrIboUg6l6uc1lhtGVI3tY2JSyy92T1ZoR+Z+1eFMaK6D34G5a2Hemc1yTdLF3EeLybXCR7r6WPPIV2607c+oX0mmmcrANJYUv1+aUS/Js2kLXUWvrymLSzt2xO2b0iG/7Gas3wXfIXLVFaDng8V+YBL8Asnvl2dNra6U8YstD0nZ978/OpwtuqTIeukVDtfynnt7RAAQxvla1086znJgefoJMjWhvGk4lbrDULLD69Na014u5Vjd6XjARPNq3rBz2rBIEJlW0EQfYTpZ9GjMsFoo5Jw4Ud4scLWdoWbr9KZo15QPI5eN8YiESb6fpgLLkIiAp8P36n50xYgC3zx4xV1vlKGbHStbKSBHw6GO3eI1CGMLMNHlYfeLklqc3gfgZ2/Z0VbAWECBxfWvFk/L396xFFpmhSsdqoeC8vBjDcgTrghwvgdz+Iy/nk+RE/tm1GU5t7P9om+REbS+oSJZeUY6gsjqszm3+u45qMX94AVfDd0izuM/hQrnunB0a3NZDp2Mld7QkGfZFQdAbw9aTvR3nCynDQ0Ps8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
